
[app]
# Output path for coommits by repository
output_path = 'output\output.json'
# Repository directies, which should be searched for commits
repo_paths = [
    'C:\Users\ExampleUser\example-repo'
]
# User names used to filter commits
user_names = [
    "Example Username",
    "Another Example Username"
]
