
[app]
output_path = 'output\output.json'
repo_paths = [
    'C:\Users\xxxmo\source\repos\restaurants-dashboard'
]
user_names = [
    "Jakub Hana",
    "Jakub HÃ¡na",
    "HÃ¡na Jakub",
    "Hana Jakub",
    "jakub.hana"
]